// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCncYxj6P0ujjENDMStmt89ZMDWTScOQbI',
    appId: '1:409717113916:web:dea7fd5d58193bdb1fef39',
    messagingSenderId: '409717113916',
    projectId: 'mobile-project-ffb9d',
    authDomain: 'mobile-project-ffb9d.firebaseapp.com',
    storageBucket: 'mobile-project-ffb9d.appspot.com',
    measurementId: 'G-PXFPRTM6G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCict9-Ou8RelaJkXUwNkLl4ceZnydrnbs',
    appId: '1:409717113916:android:1e5e74ab402d19d71fef39',
    messagingSenderId: '409717113916',
    projectId: 'mobile-project-ffb9d',
    storageBucket: 'mobile-project-ffb9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-4eIleDj0J-RFISBksMOUlgmbB8uQfE',
    appId: '1:409717113916:ios:26141dc267ba0cae1fef39',
    messagingSenderId: '409717113916',
    projectId: 'mobile-project-ffb9d',
    storageBucket: 'mobile-project-ffb9d.appspot.com',
    iosBundleId: 'com.example.metrofood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-4eIleDj0J-RFISBksMOUlgmbB8uQfE',
    appId: '1:409717113916:ios:f6ead8ade835f6a01fef39',
    messagingSenderId: '409717113916',
    projectId: 'mobile-project-ffb9d',
    storageBucket: 'mobile-project-ffb9d.appspot.com',
    iosBundleId: 'com.example.metrofood.RunnerTests',
  );
}
